In [3]:
import tensorflow as tf
import numpy as np

In [4]:
sess = tf.Session()
# Create example y_hat.
#we have batch_size=2 and we have 3 classes
y_hat = tf.convert_to_tensor(np.array([[0.5, 1.5, 0.1],[2.2, 1.3, 1.7]]))
sess.run(y_hat)
# We can see values are not normalized it did not add upto 1
#to that we can add tf.softmax function

array([[0.5, 1.5, 0.1],
       [2.2, 1.3, 1.7]])

In [5]:
y_hat_softmax = tf.nn.softmax(y_hat)
sess.run(y_hat_softmax)
#now the value normalizes it the row values now added upto 1
# we can treat it like the probability
#Since for the first row 2nd probability is higher(0.61) it will predict as class 2
# For the second row 1st probability is higher(0.49) it will predict as class 1

array([[0.227863  , 0.61939586, 0.15274114],
       [0.49674623, 0.20196195, 0.30129182]])

In [6]:
y_true = tf.convert_to_tensor(np.array([[0.0, 1.0, 0.0],[0.0, 0.0, 1.0]]))
sess.run(y_true)

array([[0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#Using cross entropy formula we can calculate the loss for each training example
#in our example it is 2
#So 2 loss will be there
loss_per_instance_2 = tf.nn.softmax_cross_entropy_with_logits(logits = y_hat, labels = y_true)
print(sess.run(loss_per_instance_2))
# array([ 0.4790107 ,  1.19967598])
#And if we want to calculate the overall loss of 2 training examples we can apply tf.reduce_mean
#Which will give a loss based on a batch
total_loss_2 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = y_hat, labels = y_true))
print(sess.run(total_loss_2))
# 0.83934333897877922

[0.4790107  1.19967598]
0.8393433389787792


In [10]:
(0.47+1.19)/2

0.83

In [14]:
-np.log(0.6193)

0.47916547103812185

In [15]:
#t.equal returns if the predicted and the actual value are same or not
#for first training example it is same so it true for second training example it is not same 
#so it return false
correct_prediction = tf.equal(tf.argmax(y_true, 1), tf.argmax(y_hat, 1))
#accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
sess.run(correct_prediction)

array([ True, False])

In [16]:
#tf.cast means we are converting some datatype to another datatype
#here the boolean value converted to the float type
#true changes to 1 and false changes to 0 
sess.run(tf.cast(correct_prediction, tf.float32))

array([1., 0.], dtype=float32)

In [17]:
#then taking mean of the two training examples which is 0.5
#so the accuracy is 50%(one rightly predicted and one wrongly predicted)
sess.run(tf.reduce_mean(tf.cast(correct_prediction, tf.float32)))

0.5